In [1]:
import numpy as np
import pandas as pd

### NUMPY Task 1 

In [5]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [6]:
mean_a = []

In [7]:
mean_a.append(a.mean(axis = 1))

In [8]:
mean_a

[array([2. , 8.4])]

### Task 2

In [9]:
mean_a = np.array(mean_a)

In [10]:
mean_a

array([[2. , 8.4]])

In [11]:
mean_a = mean_a.reshape(2,1)
mean_a

array([[2. ],
       [8.4]])

In [12]:
a_centered = a - mean_a
a_centered

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

### Task 3

In [13]:
fi = a_centered[:1, :5].flatten()
fi

array([-1.,  0.,  1.,  1., -1.])

In [14]:
ti = a_centered[1:, 0:5].flatten()
ti

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [15]:
a_centered_sp = np.dot(fi,ti)
a_centered_sp

8.0

In [16]:
a_centered.shape

(2, 5)

In [17]:
N = 5-1
N

4

In [18]:
a_centered_sp = a_centered_sp / N
a_centered_sp

2.0

### Task 4

In [19]:
check_cov = np.cov(m = a)
check_cov

array([[1. , 2. ],
       [2. , 4.3]])

In [20]:
check_cov[0][1] == a_centered_sp

True

### PANDAS Task 1

In [2]:
authors = pd.DataFrame({'Author_id' : [1, 2, 3], 'Author_name' : ['Turgenev', 'Chekhov', 'Ostrovsky']}, columns = ['Author_id', 'Author_name'])
authors

Author_id Author_name
0          1    Turgenev
1          2     Chekhov
2          3   Ostrovsky

In [3]:
book = pd.DataFrame({'Author_id' : [1, 1, 1, 2, 2, 3, 3], 'Book_title' : ['Fathers and Sons', 'Rudin', 'Home of the Gentry', 'Fat and Thin', 'The Lady with the Dog', 'Thunderstorm', 'Talents and Fans'], 'Price' : [450, 300, 350, 500, 450, 370, 290]})
book

Author_id             Book_title  Price
0          1       Fathers and Sons    450
1          1                  Rudin    300
2          1     Home of the Gentry    350
3          2           Fat and Thin    500
4          2  The Lady with the Dog    450
5          3           Thunderstorm    370
6          3       Talents and Fans    290

### Task 2

In [4]:
authors_price = pd.merge(authors, book, on = 'Author_id', how= 'inner')
authors_price

Author_id Author_name             Book_title  Price
0          1    Turgenev       Fathers and Sons    450
1          1    Turgenev                  Rudin    300
2          1    Turgenev     Home of the Gentry    350
3          2     Chekhov           Fat and Thin    500
4          2     Chekhov  The Lady with the Dog    450
5          3   Ostrovsky           Thunderstorm    370
6          3   Ostrovsky       Talents and Fans    290

### Task 3

In [5]:
top5 = authors_price.nlargest(5, 'Price')
top5

Author_id Author_name             Book_title  Price
3          2     Chekhov           Fat and Thin    500
0          1    Turgenev       Fathers and Sons    450
4          2     Chekhov  The Lady with the Dog    450
5          3   Ostrovsky           Thunderstorm    370
2          1    Turgenev     Home of the Gentry    350

### Task 4

In [66]:
df1 = authors_price.groupby('Author_name')['Price'].min()

In [47]:
df2 = authors_price.groupby('Author_name')['Price'].max()

In [48]:
df3 = authors_price.groupby('Author_name')['Price'].mean()

In [55]:
author_stat = pd.concat([df1, df2, df3], axis=1)
author_stat

Price  Price       Price
Author_name                          
Chekhov        450    500  475.000000
Ostrovsky      290    370  330.000000
Turgenev       300    450  366.666667

### Второй вариант решения

In [73]:
author_stat_1 = pd.merge(df2, df3, on = 'Author_name', how='inner')

In [74]:
author_stat_2 = pd.merge(authors['Author_name'], df1, on ='Author_name', how='inner')

In [77]:
author_stat = pd.merge(author_stat_2, author_stat_1, on='Author_name',how='inner')

Author_name  Price  Price_x     Price_y
0    Turgenev    300      450  366.666667
1     Chekhov    450      500  475.000000
2   Ostrovsky    290      370  330.000000

In [84]:
author_stat = author_stat.rename(columns={'Price' : 'Min_price', 'Price_x' : 'Max_price', 'Price_y' : 'Mean_price'})
author_stat

Author_name  Min_price  Max_price  Mean_price
0    Turgenev        300        450  366.666667
1     Chekhov        450        500  475.000000
2   Ostrovsky        290        370  330.000000

### Task 5

In [86]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

Author_id Author_name             Book_title  Price    cover
0          1    Turgenev       Fathers and Sons    450  твердая
1          1    Turgenev                  Rudin    300   мягкая
2          1    Turgenev     Home of the Gentry    350   мягкая
3          2     Chekhov           Fat and Thin    500  твердая
4          2     Chekhov  The Lady with the Dog    450  твердая
5          3   Ostrovsky           Thunderstorm    370   мягкая
6          3   Ostrovsky       Talents and Fans    290   мягкая

In [129]:
book_info = pd.pivot_table(authors_price, index='Author_name', columns='cover', values='Price', aggfunc=np.sum)
book_info

cover        мягкая  твердая
Author_name                 
Chekhov         NaN    950.0
Ostrovsky     660.0      NaN
Turgenev      650.0    450.0

In [130]:
book_info['твердая'].fillna('0', inplace = True)

In [131]:
book_info['мягкая'].fillna('0', inplace = True)
book_info

cover       мягкая твердая
Author_name               
Chekhov          0   950.0
Ostrovsky    660.0       0
Turgenev     650.0   450.0

In [133]:
book_info.to_pickle("book_info.pkl")

In [136]:
book_info2 = pd.read_pickle("book_info.pkl")
book_info2

cover       мягкая твердая
Author_name               
Chekhov          0   950.0
Ostrovsky    660.0       0
Turgenev     650.0   450.0